var crops = {
	//Vanilla crops start here:
	"amaranth": {
		"Mod": "Vanilla",
		"Product": "Amaranth",
		"SeedName": "Amaranth Seeds",
		"URL": "https://stardewvalleywiki.com/Amaranth",
		"Description": "A purple grain cultivated by an ancient civilization.",
		"Type": "Vegetable",
		"Seasons": ["fall"],
		"GrowthTime": 7,
		"RegrowthTime": 0,
		"Bonus":
		{
			"MinimumPerHarvest": 1,
			"MaximumPerHarvest": 1,
			"MaxIncreasePerFarmLevel": 5,
			"ExtraChance": 0.0,
		},
		"SeedPurchasePrice": 70,
		"JojaPurchasePrice": 87,
		"ProduceValue": 150,
	},
	"ancientfruit": {
		"Mod": "Vanilla",
		"Product": "Ancient Fruit",
		"SeedName": "Ancient Seeds",
		"URL": "https://stardewvalleywiki.com/Ancient_Fruit",
		"Description": "It's been dormant for eons.",
		"Type": "Fruit",
		"Seasons": ["spring", "summer", "fall"],
		"GrowthTime": 28,
		"RegrowthTime": 7,
		"Bonus":
		{
			"MinimumPerHarvest": 1,
			"MaximumPerHarvest": 1,
			"MaxIncreasePerFarmLevel": 5,
			"ExtraChance": 0.0,
		},
		"SeedPurchasePrice": 0,
		"JojaPurchasePrice": 0,
		"ProduceValue": 550,
	},
	"artichoke": {
		"Mod": "Vanilla",
		"Product": "Artichoke",
		"SeedName": "Artichoke Seeds",
		"URL": "https://stardewvalleywiki.com/Artichoke",
		"Description": "The bud of a thistle plant. The spiny outer leaves conceal a fleshy, filling interior.",
		"Type": "Vegetable",
		"Seasons": ["fall"],
		"GrowthTime": 8,
		"RegrowthTime": 0,
		"Bonus":
		{
			"MinimumPerHarvest": 1,
			"MaximumPerHarvest": 1,
			"MaxIncreasePerFarmLevel": 5,
			"ExtraChance": 0.0,
		},
		"SeedPurchasePrice": 30,
		"JojaPurchasePrice": 0,
		"ProduceValue": 160,
	},
	"beet": {
		"Mod": "Vanilla",
		"Product": "Beet",
		"SeedName": "Beet Seeds",
		"URL": "https://stardewvalleywiki.com/Beet",
		"Description": "A sweet and earthy root vegatable. As a bonus, the leaves make a great salad.",
		"Type": "Vegetable",
		"Seasons": ["fall"],
		"GrowthTime": 6,
		"RegrowthTime": 0,
		"Bonus":
		{
			"MinimumPerHarvest": 1,
			"MaximumPerHarvest": 1,
			"MaxIncreasePerFarmLevel": 5,
			"ExtraChance": 0.0,
		},
		"SeedPurchasePrice": 20,
		"JojaPurchasePrice": 0,
		"ProduceValue": 100,
	},
	"bluejazz": {
		"Mod": "Vanilla",
		"Product": "Blue Jazz",
		"SeedName": "Jazz Seeds",
		"URL": "https://stardewvalleywiki.com/Blue_Jazz",
		"Description": "The flower grows in a sphere to invite as many butterflies as possible.",
		"Type": "Flower",
		"Seasons": ["spring"],
		"GrowthTime": 7,
		"RegrowthTime": 0,
		"Bonus":
		{
			"MinimumPerHarvest": 1,
			"MaximumPerHarvest": 1,
			"MaxIncreasePerFarmLevel": 5,
			"ExtraChance": 0.0,
		},
		"SeedPurchasePrice": 30,
		"JojaPurchasePrice": 37,
		"ProduceValue": 50,
	},
	"blueberry": {
		"Mod": "Vanilla",
		"Product": "Blueberry",
		"SeedName": "Blueberry Seeds",
		"URL": "https://stardewvalleywiki.com/Blueberry",
		"Description": "A popular berry reported to have many health benefits. The blue skin has the highest nutrient concentration.",
		"Type": "Fruit",
		"Seasons": ["summer"],
		"GrowthTime": 13,
		"RegrowthTime": 4,
		"Bonus":
		{
			"MinimumPerHarvest": 3,
			"MaximumPerHarvest": 4,
			"MaxIncreasePerFarmLevel": 5,
			"ExtraChance": 0.02,
		},
		"SeedPurchasePrice": 80,
		"JojaPurchasePrice": 0,
		"ProduceValue": 50,
	},
	"bokchoy": {
		"Mod": "Vanilla",
		"Product": "Bok Choy",
		"SeedName": "Bok Choy Seeds",
		"URL": "https://stardewvalleywiki.com/Bok_Choy",
		"Description": "The leafy greens and fibrous stalks are healthy and delicious.",
		"Type": "Vegetable",
		"Seasons": ["fall"],
		"GrowthTime": 4,
		"RegrowthTime": 0,
		"Bonus":
		{
			"MinimumPerHarvest": 1,
			"MaximumPerHarvest": 1,
			"MaxIncreasePerFarmLevel": 5,
			"ExtraChance": 0.0,
		},
		"SeedPurchasePrice": 50,
		"JojaPurchasePrice": 62,
		"ProduceValue": 80,
	},
	"cactusfruit": {
		"Mod": "Vanilla",
		"Product": "Cactus Fruit",
		"SeedName": "Cactus Seeds",
		"URL": "https://stardewvalleywiki.com/Cactus_Fruit",
		"Description": "The sweet fruit of the prickly pear cactus.",
		"Type": "Fruit",
		"Seasons": [],
		"GrowthTime": 12,
		"RegrowthTime": 3,
		"Bonus":
		{
			"MinimumPerHarvest": 1,
			"MaximumPerHarvest": 1,
			"MaxIncreasePerFarmLevel": 5,
			"ExtraChance": 0.0,
		},
		"SeedPurchasePrice": 150,
		"JojaPurchasePrice": 0,
		"ProduceValue": 75,
	},
		"cactusfruit": {
		"Mod": "Vanilla",
		"Product": "Cactus Fruit",
		"SeedName": "Cactus Seeds",
		"URL": "https://stardewvalleywiki.com/Cactus_Fruit",
		"Description": "The sweet fruit of the prickly pear cactus.",
		"Type": "Fruit",
		"Seasons": [],
		"GrowthTime": 12,
		"RegrowthTime": 3,
		"Bonus":
		{
			"MinimumPerHarvest": 1,
			"MaximumPerHarvest": 1,
			"MaxIncreasePerFarmLevel": 5,
			"ExtraChance": 0.0,
		},
		"SeedPurchasePrice": 150,
		"JojaPurchasePrice": 0,
		"ProduceValue": 75,
	},
	"cauliflower": {
		"Mod": "Vanilla",
		"Product": "Cauliflower",
		"SeedName": "Cauliflower Seeds",
		"URL": "https://stardewvalleywiki.com/Cauliflower",
		"Description": "Valuable, but slow-growing. Despite its pale color, the florets are packed with nutrients.",
		"Type": "Vegetable",
		"Seasons": ["spring"],
		"GrowthTime": 12,
		"RegrowthTime": 0,
		"Bonus":
		{
			"MinimumPerHarvest": 1,
			"MaximumPerHarvest": 1,
			"MaxIncreasePerFarmLevel": 5,
			"ExtraChance": 0.0,
		},
		"SeedPurchasePrice": 80,
		"JojaPurchasePrice": 100,
		"ProduceValue": 175,
	},
};